export default {
  CATEGORY: 'Category',
  BOOKMARKS: 'Bookmarks',
  MORE: 'More',
  BUY: 'Buy',
  SEARCH: 'Search',
  TABROUTES: 'TabRoutes',
  SUBCATONE: 'Subcatone',
  URLS: 'urls',
  SUBCATTWO: 'Subcattwo',
  SUBCATTHREE: 'Subcatthree',
  SUBCATFOUR: 'Subcatfour',
  SUBCATFIVE: 'Subcatfive',
  SUBCATSIX: 'Subcatsix',
  SUBCATSEVEN: 'Subcatseven',
  SUBCATEIGHT: 'Subcateight',
  SUBCATNINE: 'Subcatnine',
  SUBCATTEN: 'Subcatten',
  SUBCATELEVEN: 'Subcateleven',
  LOGIN: 'Login',
};
